In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("excell.xlsx")

In [6]:
df

,Unnamed: 0,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift
0,0,1,Olivia,23.0,Teacher,369036,0,No_Bonus
1,1,2,Sophia,20.0,Boxer,239144,2,No_Bonus
2,2,3,Jake,38.0,Scientist,349794,1,No_Bonus
3,3,4,Rocky,56.0,Chef,235840,2,Bonus
4,4,4,Rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,275858,0,Bonus
496,496,497,Sherlock,46.0,Boxer,79740,6,Bonus
497,497,498,Sherlock,47.0,Detective,331902,5,No_Bonus
498,498,499,Olivia,55.0,Comedian,385236,5,No_Bonus
499,499,500,Sherlock,59.0,Software Engineer,389772,28,No_Bonus

In [9]:
df = df.drop("Unnamed: 0", axis = 1)

In [10]:
df

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift
0,1,Olivia,23.0,Teacher,369036,0,No_Bonus
1,2,Sophia,20.0,Boxer,239144,2,No_Bonus
2,3,Jake,38.0,Scientist,349794,1,No_Bonus
3,4,Rocky,56.0,Chef,235840,2,Bonus
4,4,Rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,Bonus
496,497,Sherlock,46.0,Boxer,79740,6,Bonus
497,498,Sherlock,47.0,Detective,331902,5,No_Bonus
498,499,Olivia,55.0,Comedian,385236,5,No_Bonus
499,500,Sherlock,59.0,Software Engineer,389772,28,No_Bonus

# Group the data based upon profession

In [14]:
df.groupby("Profession")["Salary"].mean()

Profession
Artist               249101.512195
Boxer                207791.735849
Chef                 221613.241379
Comedian             245378.000000
Detective            241929.955556
Doctor               227928.666667
Pilot                217282.943396
Scientist            253338.962963
Software Engineer    235817.882353
Teacher              215845.422222
Name: Salary, dtype: float64

In [15]:
# Find average salary based upon the profession

df.groupby("Profession")["Salary"].mean()

Profession
Artist               249101.512195
Boxer                207791.735849
Chef                 221613.241379
Comedian             245378.000000
Detective            241929.955556
Doctor               227928.666667
Pilot                217282.943396
Scientist            253338.962963
Software Engineer    235817.882353
Teacher              215845.422222
Name: Salary, dtype: float64

In [16]:
# Group the data based upon multiple column
df.groupby(["Profession", "Age"])["Salary"].mean()

Profession  Age
Artist      20.0    248462.000000
            21.0    199906.000000
            22.0    378053.000000
            25.0    180724.666667
            26.0    206281.000000
                        ...
Teacher     56.0    102844.000000
            57.0    174367.333333
            58.0    117635.000000
            59.0    304606.000000
            60.0    327156.000000
Name: Salary, Length: 278, dtype: float64

In [19]:
# agg(): aggregation function

df.groupby(["Profession", "Age"])["Salary"].agg(["mean", "count"])

                          mean  count
Profession Age
Artist     20.0  248462.000000      1
           21.0  199906.000000      1
           22.0  378053.000000      2
           25.0  180724.666667      3
           26.0  206281.000000      2
...                        ...    ...
Teacher    56.0  102844.000000      1
           57.0  174367.333333      3
           58.0  117635.000000      2
           59.0  304606.000000      1
           60.0  327156.000000      1

[278 rows x 2 columns]

In [20]:
df[["Age", "Salary"]].agg(["mean", "sum", "min", "max"])

               Age        Salary
mean     40.810976  2.312057e+05
sum   20079.000000  1.156028e+08
min      20.000000  6.032800e+04
max      60.000000  3.990580e+05

In [21]:
# apply different aggregation functions to different columns

In [22]:
df.agg({
    "Age": ["min", "mean"],
    "Salary": ["max", "mean"]
})

            Age      Salary
min   20.000000         NaN
mean  40.810976  231205.656
max         NaN  399058.000

In [24]:
# agg(): groupby()
df.groupby("Profession").agg(
    {
    "Age": ["min", "mean"],
    "Salary": ["max", "mean"]
})

                    Age             Salary
                    min       mean     max           mean
Profession
Artist             20.0  36.736842  395370  249101.512195
Boxer              20.0  39.547170  399058  207791.735849
Chef               20.0  43.344828  392988  221613.241379
Comedian           20.0  40.038462  397694  245378.000000
Detective          20.0  41.477273  389942  241929.955556
Doctor             22.0  43.152174  397956  227928.666667
Pilot              20.0  39.711538  398634  217282.943396
Scientist          22.0  41.000000  396190  253338.962963
Software Engineer  21.0  41.120000  396570  235817.882353
Teacher            20.0  41.022222  372254  215845.422222

In [25]:
# Merging of DataFrame
# merge(): this function can be used to merge the dataframes based upon common column.
# merge(): function work like join in sql: inner, left, right, outer.

In [27]:
df1 = pd.DataFrame({
    "ID" : [1,2,3],
    "Dream_company": ["google", "microsoft", "Apple"]
})
df2 = pd.DataFrame({
    "ID": [2,3,4],
    "Dream_package": [50,60,40]
})

merge_df = pd.merge(df1, df2, on = "ID")  # by default it shows inner join
merge_df

   ID Dream_company  Dream_package
0   2     microsoft             50
1   3         Apple             60

In [28]:
merge_df = pd.merge(df1, df2, on = "ID", how = "left")  # by default it shows inner join
merge_df

   ID Dream_company  Dream_package
0   1        google            NaN
1   2     microsoft           50.0
2   3         Apple           60.0

In [29]:
merge_df = pd.merge(df1, df2, on = "ID", how = "right")  # by default it shows inner join
merge_df

   ID Dream_company  Dream_package
0   2     microsoft             50
1   3         Apple             60
2   4           NaN             40

In [30]:
merge_df = pd.merge(df1, df2, on = "ID", how = "outer")  # by default it shows inner join
merge_df

   ID Dream_company  Dream_package
0   1        google            NaN
1   2     microsoft           50.0
2   3         Apple           60.0
3   4           NaN           40.0

# join(): mainly used to work with index

In [37]:
df3 = pd.DataFrame({
    "Hero_Name": ["NTR", "Prabhas", "Mahesh_Babu"]},
    index = [1,2,3]
)

df4 = pd.DataFrame({
    "Heroine_Name": ["C", "A", "R"]},
    index = [2,3,4]
)

joined_df = df3.join(df4, how = "inner")
joined_df

     Hero_Name Heroine_Name
2      Prabhas            C
3  Mahesh_Babu            A

# concat()

In [38]:
# def: concat() function is used to stack dataframes vertically or horizontally

In [43]:
df5 = pd.DataFrame({"ID": [1,2], "Fav_Movie": ["Paradise", "Bahubali"]})
df6 = pd.DataFrame({
    "ID": [3,4],
    "Fav_Movie": ["SpiderMan", "Dhoom2"]
})
df7 = pd.DataFrame({
    "ID": [5,6],
    "Fav_Movie": ["Pushpa", "Badrinath"]
})
# axis = 0: vertically [adding rows],
# axis = 1: Horizontally [adding column]

concat_df = pd.concat([df5, df6,df7], axis = 0, ignore_index = True)
concat_df

   ID  Fav_Movie
0   1   Paradise
1   2   Bahubali
2   3  SpiderMan
3   4     Dhoom2
4   5     Pushpa
5   6  Badrinath

# Time series based dataframe

In [47]:
# date_range() pandas function is used for generating data related data.
date_rng = pd.date_range(start = "2020-01-01", end = "2026-12-31", freq = "YE")
date_rng

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [48]:
date_rng = pd.date_range(start = "2020-01-01", end = "2026-12-31", freq = "YS")
date_rng

DatetimeIndex(['2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01',
               '2024-01-01', '2025-01-01', '2026-01-01'],
              dtype='datetime64[us]', freq='YS-JAN')

In [49]:
date_rng = pd.date_range(start = "2020-01-01", end = "2026-12-31", freq = "ME")
date_rng

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[us]', freq='ME')

In [51]:
date_rng = pd.date_range(start = "2020-01-01", end = "2026-12-31", freq = "D")
date_rng

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=2557, freq='D')

In [4]:
date_rng = pd.date_range(start = "2020-01-01", end = "2026-12-31", freq = "h")
date_rng

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00', '2020-01-01 07:00:00',
               '2020-01-01 08:00:00', '2020-01-01 09:00:00',
               ...
               '2026-12-30 15:00:00', '2026-12-30 16:00:00',
               '2026-12-30 17:00:00', '2026-12-30 18:00:00',
               '2026-12-30 19:00:00', '2026-12-30 20:00:00',
               '2026-12-30 21:00:00', '2026-12-30 22:00:00',
               '2026-12-30 23:00:00', '2026-12-31 00:00:00'],
              dtype='datetime64[us]', length=61345, freq='h')