In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [5]:
df["Profession"].unique()

<ArrowStringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [7]:
df["Profession"].value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [8]:
# describe() function is used for statistical information
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

In [9]:
# count = number of non-null values
# mean = average
# std = standard deviation: how much data is for away from mean.
# percentile: from how many people i am ahead

In [10]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='str')

In [11]:
# describing the categorical columns
df.describe(include= "object")

C:\Users\KALLY\AppData\Local\Temp\ipykernel_13492\3501404678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include= "object")

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

In [13]:
df["Name"].unique()

<ArrowStringArray>
[   'olivia', 'sophia   ',      'jake',     'Rocky',      'Jake',    'Olivia',
      'John',  'Sherlock',     'Alice',  'Mr. Bean',    'Sophia',      'Liam',
      'Emma']
Length: 13, dtype: str

In [12]:
df["Name"].nunique()

13

In [14]:
df["Profession"].value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

# Data filtering and indexing

In [17]:
# Query: find those records where salary > 10000

df[df["salary"] > 100000]

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
493  494     Sophia  39.0             Doctor  174500                        0
495  496       John  45.0              Boxer  137929                        0
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[304 rows x 6 columns]

In [18]:
df[df["salary"] < 50000]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
13    14      John  46.0             Artist   43078                       12
39    40    Olivia  60.0  Software Engineer   32286                        1
40    41     Alice  52.0               Chef   46535                        4
41    42     Rocky  39.0             Doctor   39660                        7
49    50      Liam  59.0              Pilot   37285                       21
..   ...       ...   ...                ...     ...                      ...
447  448  Mr. Bean  59.0             Doctor   37507                       15
462  463    Sophia  32.0          Detective   31851                        3
489  490      John  56.0          Scientist   41192                        7
494  495     Rocky  27.0             Doctor   46975                        0
496  497  Sherlock  46.0              Boxer   39870                        6

[64 rows x 6 columns]

In [19]:

df[(df["salary"] > 50000) & (df["salary"] < 100000)]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
10    11     Rocky   NaN             Doctor   75543                        5
15    16  Sherlock  30.0              Boxer   57774                        0
23    24  Sherlock  42.0              Boxer   92995                        2
26    27     Alice  48.0              Pilot   99949                        4
28    29     Alice  21.0               Chef   84792                        3
..   ...       ...   ...                ...     ...                      ...
479  480      Liam  26.0              Pilot   80708                        3
481  482    Olivia  56.0  Software Engineer   71404                        5
487  488  Sherlock  49.0              Pilot   82386                        2
488  489      Emma  21.0  Software Engineer   92013                        2
492  493      John  55.0             Artist   57720                        2

[132 rows x 6 columns]

In [20]:

df[(df["salary"] > 50000) & (df["salary"] < 100000)].shape

(132, 6)

In [21]:
# Query: find those records wheere salary < 50000 or salary >150000
df[(df["salary"] < 50000) | (df["salary"] > 150000)]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
0      1    olivia  23.0            Teacher  184518                        0
2      3      jake  38.0          Scientist  174897                        1
11    12      Jake   NaN             Artist  174780                        5
13    14      John  46.0             Artist   43078                       12
14    15      Jake  40.0               Chef  171553                        3
..   ...       ...   ...                ...     ...                      ...
494  495     Rocky  27.0             Doctor   46975                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[217 rows x 6 columns]

In [24]:
# Query: find the record of the person who get maximum salary.
df[df["salary"] == df["salary"].max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [25]:
# find the record of the person who got max marriage proposals
df[df["Marriage_proposal_count"] == df["Marriage_proposal_count"].max()]

      ID   Name   Age Profession  salary  Marriage_proposal_count
399  400  Rocky  52.0   Comedian   69267                       40

In [28]:
# Query: find the record of the person who got minimum salary
df[df["salary"] == df["salary"].min()][['Name', "Profession"]]

         Name Profession
213  Sherlock       Chef

# Indexing

In [29]:
# loc and iloc

In [31]:
# Query: Print 1 to 6 records and Name to profession columns
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='str')

In [33]:
# Query: Print 1 to 6 records and Name to profession columns
# df.loc[row: columns]
df.loc[1:6, "Name" : "Profession"]

        Name   Age   Profession
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [39]:
# Query: Print 10 to 20 records and Age to salary columns
df.loc[10:20:2, ["Age","salary"]]

     Age  salary
10   NaN   75543
12  22.0  102063
14  40.0  171553
16  46.0  135907
18  25.0  181312
20  40.0  118998

In [36]:
df.iloc[1:6, 0 : 5]

   ID       Name   Age   Profession  salary
1   2  sophia     20.0        Boxer  119572
2   3       jake  38.0    Scientist  174897
3   4      Rocky  56.0         Chef  117920
4   4      Rocky  56.0         Chef  117920
5   4      Rocky  56.0         Chef  117920

In [45]:
# iloc
# Query: print record from 1 to 6 and columns from 1 to 3
df.iloc[0:7, 1:4]

        Name   Age   Profession
0     olivia  23.0      Teacher
1  sophia     20.0        Boxer
2       jake  38.0    Scientist
3      Rocky  56.0         Chef
4      Rocky  56.0         Chef
5      Rocky  56.0         Chef
6      Rocky  56.0         Chef

In [46]:
# Interview question: What is the difference loc and iloc
# in loc we need to mention the column names
# while in iloc we mention the index of columns
# iloc goes up to n-1, but loc goes upto nth value

# iloc is little faster than loc
# because loc need to convert column names to index

In [47]:
df.iloc[0,1]

'olivia'

In [48]:
df.iloc[0,2]

23.0

In [49]:
df.at[0, "Name"]

'olivia'

In [51]:
df.iat[0,1]

'olivia'

In [ ]:
# at & iat used specifically to access single element
# at & iat are faster than loc & iloc