In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

# Handling Null Values

In [5]:
# Null: The information which is not provided
# NaN, na
# Null vs 0
# 0 is a value, while Null means no value available.

In [6]:
# identify the null values in dataframe
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [7]:
df.isna().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [10]:
# find the null values in a specific column
df[df["Age"].isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [11]:
# print 
df["Age"].isnull().sum()

8

In [14]:
# Delete the records which is having null values
df1 = df.copy()
df1.dropna(inplace = True)

In [15]:
df1.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [16]:
df1.shape

(492, 6)

In [18]:
# Why we need to handle the null values
# Ans: inbuild functions might not work properly (numpy and python)
# Pandas function can work but will give the wrong answer as it will not include the NaN value.

import numpy as np
vals = [10, 20, 30, 40, np.nan]
np.mean(vals)

nan

In [20]:
df['Age'].mean()

40.8109756097561

In [22]:
# series
ser1 = pd.Series(
    vals
)
ser1.mean()

25.0

In [25]:
# Approach-1: delete the records which is having null values
# Approach-2: delete the columns which is having the null values
df2 = df.copy()

In [26]:
df2.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [27]:
# axis =1: delete the column which is having null value
# axis = 0: delete the row which is having null value
# how = "any" : delete the column even that have single null value
# how = "all" : delete the column only if all the values in that column is NULL
df2 = df2.dropna(axis = 1, how = "all")
df2.isnull().sum()

ID                         0
Name                       0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [32]:
# Approach-3: replace the null value with same constant
df3 = df.copy()

In [37]:
# fillna() function is used to fill the null values with some other value
print(df3["Age"].mean())
df3["Age"] = df3["Age"].fillna(df3["Age"].mean())

40.8109756097561

In [38]:
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [39]:
df3.shape

(500, 6)

# Handle Duplicate values

In [40]:
# Identify the duplicate records
df.duplicated().sum()

3

In [41]:
# show the duplicate records 
# if a record is completely matching with same other record
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [45]:
# keep = False: show both the records
# - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
# - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
# - False : Mark all duplicates as ``True``
df[df.duplicated(keep = False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [46]:
df[df.duplicated(keep = "last")]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2

In [47]:
df[df.duplicated(keep = "first")]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [48]:
# Deleting the duplicate records
df = df.drop_duplicates()

In [49]:
df.duplicated().sum()

0