# Loading data from SQL/ JSON file

In [2]:
import pandas as pd

In [3]:
import sqlite3

In [5]:
# Created empty database connections 
conn = sqlite3.connect("Ds20_database.db")

In [7]:
# Reading the excel file as DataFrame
df = pd.read_excel("Excel_data.xlsx")
# Stroing the df as table in the database
df.to_sql("Table1", conn, if_exists="replace")

500

In [10]:
df1 = pd.read_sql("select * from Table1", conn)
df1

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

# Loading/Storing data from JSON

In [11]:
df2 = pd.read_json("json_data.json")
df2

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

# Understand the dataset using pandas

In [12]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [13]:
# shape keyword will return "rows" and "columns"
df.shape

(500, 6)

In [15]:
# head() function returns top 5 records in pandas by default
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [16]:
# return bottom 5 records by default
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [19]:
# Query: print Name column only
df[["Name"]]

          Name
0       olivia
1    sophia
2         jake
3        Rocky
4        Rocky
..         ...
495       John
496   Sherlock
497   Sherlock
498     Olivia
499   Sherlock

[500 rows x 1 columns]

In [21]:
# print multiple columns (Age and salary)
df[["Age", "salary", "Profession"]]

      Age  salary         Profession
0    23.0  184518            Teacher
1    20.0  119572              Boxer
2    38.0  174897          Scientist
3    56.0  117920               Chef
4    56.0  117920               Chef
..    ...     ...                ...
495  45.0  137929              Boxer
496  46.0   39870              Boxer
497  47.0  165951          Detective
498  55.0  192618           Comedian
499  59.0  194886  Software Engineer

[500 rows x 3 columns]

In [22]:
# rename the columns
df2 = df.rename(columns = {"Name" : "Peru", "Age": "Vayasu", "Profession": "Vruthi"})
df2

,ID,Peru,Vayasu,Vruthi,salary,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5
499,500,Sherlock,59.0,Software Engineer,194886,28

In [28]:
# Add a new column in dataset
# rank() function provide the rank based upon the salary
# Lower salary = Lower rank
df["rank"] = df.salary.rank(ascending = False)
df["rank123"] = df.salary.rank(ascending = False)
df.sort_values("rank")

# if columns already present then this will update the column
# if column don't exist then new column will be created

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,rank123
436,437,Sherlock,52.0,Boxer,199529,3,1.0,1.0
65,66,Emma,57.0,Pilot,199317,1,2.0,2.0
132,133,Rocky,31.0,Doctor,198978,8,3.0,3.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0,4.0
474,475,Sophia,30.0,Doctor,198653,1,5.0,5.0
...,...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0,496.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0,497.0
398,399,Rocky,25.0,Scientist,30659,5,498.0,498.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0,499.0
213,214,Sherlock,21.0,Chef,30164,2,500.0,500.0

# Delete column from dataframe

In [29]:
df = df.drop(["rank123"], axis = 1)
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
0,1,olivia,23.0,Teacher,184518,0,39.0
1,2,sophia,20.0,Boxer,119572,2,234.0
2,3,jake,38.0,Scientist,174897,1,75.0
3,4,Rocky,56.0,Chef,117920,2,250.0
4,4,Rocky,56.0,Chef,117920,1,250.0
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,181.0
496,497,Sherlock,46.0,Boxer,39870,6,465.0
497,498,Sherlock,47.0,Detective,165951,5,106.0
498,499,Olivia,55.0,Comedian,192618,5,21.0
499,500,Sherlock,59.0,Software Engineer,194886,28,14.0

# Replace the value in dataframe

In [31]:
df["Name"] = df["Name"].replace({"Samantha" : "Tamana", "jake": "Balakrishna"})
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
0,1,Tamana,23.0,Teacher,184518,0,39.0
1,2,sophia,20.0,Boxer,119572,2,234.0
2,3,Balakrishna,38.0,Scientist,174897,1,75.0
3,4,Rocky,56.0,Chef,117920,2,250.0
4,4,Rocky,56.0,Chef,117920,1,250.0
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,181.0
496,497,Sherlock,46.0,Boxer,39870,6,465.0
497,498,Sherlock,47.0,Detective,165951,5,106.0
498,499,Olivia,55.0,Comedian,192618,5,21.0
499,500,Sherlock,59.0,Software Engineer,194886,28,14.0

In [32]:
# all the columns datatype
df.dtypes

ID                           int64
Name                           str
Age                        float64
Profession                     str
salary                       int64
Marriage_proposal_count      int64
rank                       float64
dtype: object

In [36]:
# convert one datatype to another
df["Age"] = df["Age"].astype("Int64")
df.dtypes

ID                           int64
Name                           str
Age                          Int64
Profession                     str
salary                       int64
Marriage_proposal_count      int64
rank                       float64
dtype: object

In [37]:
# column names
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count',
       'rank'],
      dtype='str')

In [39]:
# print only categorical columns name
df.select_dtypes(include=["string", "object"]).columns

Index(['Name', 'Profession'], dtype='str')

In [40]:
# print only numerical columns name
df.select_dtypes(include=["int", "float"]).columns

Index(['ID', 'Age', 'salary', 'Marriage_proposal_count', 'rank'], dtype='str')

In [41]:
# 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    str
 2   Age                      492 non-null    Int64
 3   Profession               500 non-null    str
 4   salary                   500 non-null    int64
 5   Marriage_proposal_count  500 non-null    int64
 6   rank                     500 non-null    float64
dtypes: Int64(1), float64(1), int64(3), str(2)
memory usage: 34.6 KB

In [42]:
# intro project, techonology used, features of project,  , record video

In [43]:
# printing unique profession
df["Profession"].unique()

<ArrowStringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [44]:
# count number of people in each profession
df["Profession"].value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [45]:
df["Marriage_proposal_count"].unique()

array([ 0,  2,  1,  3, 11,  5, 12, 13,  4,  8,  7, 10, 21,  9, 14, 26, 15,
       30,  6, 38, 34, 32, 37, 40, 31, 28], dtype=int64)

In [50]:
# count no of people in each profession
df["Marriage_proposal_count"].value_counts()

Marriage_proposal_count
2     81
0     76
1     75
4     68
3     66
5     59
8      8
14     8
12     7
13     7
15     7
7      6
10     6
6      6
11     5
9      5
21     1
26     1
30     1
38     1
34     1
32     1
37     1
40     1
31     1
28     1
Name: count, dtype: int64

In [51]:
# count no of people in each profession
df.groupby("Profession").Marriage_proposal_count.sum()

Profession
      Boxer          216
Artist               138
Chef                 239
Comedian             306
Detective            219
Doctor               161
Pilot                174
Scientist            185
Software Engineer    217
Teacher              158
Name: Marriage_proposal_count, dtype: int64