# Handling inconsistent data

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [4]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='str')

In [5]:
# Make the column name consistent
# Make all the column name start with capital letter
df.columns = df.columns.str.title()   # str.lower(), str.upper()

In [6]:
df

      Id       Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [7]:
df["Name"].unique()

<ArrowStringArray>
[   'olivia', 'sophia   ',      'jake',     'Rocky',      'Jake',    'Olivia',
      'John',  'Sherlock',     'Alice',  'Mr. Bean',    'Sophia',      'Liam',
      'Emma']
Length: 13, dtype: str

In [8]:
df["Name"] = df["Name"].str.title()

In [9]:
# str.strip() remove the extra space and trailing spaces.
df["Name"] = df["Name"].str.strip()

In [10]:
df["Name"].unique()

<ArrowStringArray>
[  'Olivia',   'Sophia',     'Jake',    'Rocky',     'John', 'Sherlock',
    'Alice', 'Mr. Bean',     'Liam',     'Emma']
Length: 10, dtype: str

In [11]:
df["Profession"].unique()

<ArrowStringArray>
[          'Teacher',       '      Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [12]:
df["Profession"] = df["Profession"].str.strip()

In [13]:
df["Profession"].unique()

<ArrowStringArray>
[          'Teacher',             'Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

# Data transformation using apply() & map() function

In [14]:
# apply(): this function is used to execute lambda function
# Lambda function is one line function
# if you want to apply lambda function on DataFrame then we use the apply() function.

In [15]:
df1 = df.copy()

In [16]:
# On the festival occation: Sai Ram decided to double the employee salary.
# We applied the lambda function on a single column.
df1["Salary"] = df1["Salary"].apply(lambda x: x * 2)
df1["Salary"]

0      369036
1      239144
2      349794
3      235840
4      235840
        ...
495    275858
496     79740
497    331902
498    385236
499    389772
Name: Salary, Length: 500, dtype: int64

In [17]:
# Create a Bonus or No Bonus
# Apply function with complete DataFrame
df1["Diwali_gift"] = df1.apply(lambda row : "Bonus" if(row["Salary"] < 300000 and row["Age"] > 40) else "No_Bonus", axis = 1)
df1

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift
0,1,Olivia,23.0,Teacher,369036,0,No_Bonus
1,2,Sophia,20.0,Boxer,239144,2,No_Bonus
2,3,Jake,38.0,Scientist,349794,1,No_Bonus
3,4,Rocky,56.0,Chef,235840,2,Bonus
4,4,Rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,Bonus
496,497,Sherlock,46.0,Boxer,79740,6,Bonus
497,498,Sherlock,47.0,Detective,331902,5,No_Bonus
498,499,Olivia,55.0,Comedian,385236,5,No_Bonus
499,500,Sherlock,59.0,Software Engineer,389772,28,No_Bonus

# map()

In [18]:
# map(): this function is used for element wise transformation

In [19]:
df["Profession"].unique()

<ArrowStringArray>
[          'Teacher',             'Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [20]:
# map function 
# df1["Profession_new"] = df1["Profession_new"].map(map_dict)

# Aggregation and Grouping functions

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       500 non-null    int64
 1   Name                     500 non-null    str
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    str
 4   Salary                   500 non-null    int64
 5   Marriage_Proposal_Count  500 non-null    int64
dtypes: float64(1), int64(3), str(2)
memory usage: 30.1 KB

In [22]:
# Sum of the total
df["Salary"].sum()

57801414

In [23]:
# Average of the total salary
# mean = sum of all items / total elements
df["Salary"].mean()

115602.828

In [24]:
# Median : Middle value after sorting the data.
# even : sum the middle values / 2
df["Salary"].median()

117920.0

In [25]:
# Mode: most frequent value
# mode works with categorical data or numerical data with repeated values

df["Profession"].mode()

0    Chef
Name: Profession, dtype: str

In [26]:
df['Profession'].unique()

<ArrowStringArray>
[          'Teacher',             'Boxer',         'Scientist',
              'Chef',            'Doctor',            'Artist',
          'Comedian', 'Software Engineer',         'Detective',
             'Pilot']
Length: 10, dtype: str

In [27]:
df["Profession"].value_counts()

Profession
Chef                 58
Scientist            54
Boxer                53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [28]:
# Minimum salary
df['Salary'].min()

30164

In [29]:
# Maximum salary
df['Salary'].max()

199529

In [30]:
# Variance: how much the data far away from mean in squared terms.
df['Salary'].var()

2440791463.4653473

In [31]:
# Standard deviation: How much data far away from mean
df["Salary"].std()

49404.366846113386

In [32]:
# size: total values including null values
df1["Age"].size

500

In [33]:
# count(): total values except the null values
df1["Age"].count()

492

In [34]:
df1

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Diwali_gift
0,1,Olivia,23.0,Teacher,369036,0,No_Bonus
1,2,Sophia,20.0,Boxer,239144,2,No_Bonus
2,3,Jake,38.0,Scientist,349794,1,No_Bonus
3,4,Rocky,56.0,Chef,235840,2,Bonus
4,4,Rocky,56.0,Chef,235840,1,Bonus
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,Bonus
496,497,Sherlock,46.0,Boxer,79740,6,Bonus
497,498,Sherlock,47.0,Detective,331902,5,No_Bonus
498,499,Olivia,55.0,Comedian,385236,5,No_Bonus
499,500,Sherlock,59.0,Software Engineer,389772,28,No_Bonus

In [36]:
df1.to_excel("excell.xlsx")